default:
  SECRET_KEY: "1)bw4z!++p0vyeh)=+l374j*ke%#-r+q7ey57gut#e#5ulyns%"
  EMAIL_HOST_USER: "datakeeper1111@gmail.com"
  EMAIL_HOST_PASSWORD: "datakeeper1jgwxly8219"
  EMAIL_HOST: "smtp.gmail.com"
  EMAIL_PORT: "587"
  DATABASE_URL: "postgresql://postgres:qazwsxedcrfv@localhost:5432/my_site"


heroku:
  SECRET_KEY: 'b-_tujhec4to0t1on-f(!s-8&*a_s%89nk%hs+9*cf-sosd0*8'





